
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jwt
    username: user
    password: user
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    generate-ddl: true
  output:
    ansi:
      enabled: always
      console-logging: true
      console-pattern:
        error: "\u001b[31m%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}) [%thread] %-5level %logger{15} - %msg%n\u001b[0m"
        warn: "\u001b[33m%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}) [%thread] %-5level %logger{15} - %msg%n\u001b[0m"
        info: "\u001b[32m%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}) [%thread] %-5level %logger{15} - %msg%n\u001b[0m"
        debug: "\u001b[34m%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}) [%thread] %-5level %logger{15} - %msg%n\u001b[0m"
        trace: "\u001b[36m%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}) [%thread] %-5level %logger{15} - %msg%n\u001b[0m"
